name: Deploy to Minikube using GitHub Actions

on: [ push ]

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build Node.js Docker Image and deploy to minikube
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@latest
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t devopshint/node-app:latest .
          echo -n "verifying images:"
          docker images
      - name: Deploy to minikube
        run:
          kubectl apply -f k8s-node-app.yaml

      - name: Check Issue
        run: |
          minikube service list
          kubectl get pods
          kubectl describe service nodejs-app
          kubectl describe pod nodejs-app-68f7c7dfbc-svzch
          kubectl logs nodejs-app-68f7c7dfbc-svzch
          kubectl delete pod nodejs-app-68f7c7dfbc-svzch
          minikube dashboard
          minikube service nodejs-app --url
        shell: /usr/bin/bash -e {0}

      - name: Test service URLs
        run: |
          minikube service list
          minikube service nodejs-app --url
